function dofile (filename)
    local f = assert(loadfile(filename))
    return f()
end

f = load("i = i + 1")
--will fail with nil if there is some syntax error
--load compiles its chunk in a global environment
--f = function () i = i + 1 end is much faster


--luac -ol prog.lc prog.lua to see how opcodes generated by the compiler

--can guard
file = assert(io.open(name,"r"))

--use pcall to raise errors
local status, err = pcall(function () a = "a" + 1 end)
